[package]
name = "hello"
version = "2.3.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
coarsetime = "0.1.20"
rhai = "1.3.0"
unicode-segmentation = "1.8.0"
rusty-leveldb = "0.3.6"